Make backend build and run on Mac
I'm getting errors from sqlalchemy:
```sh
    )
TypeError: Can't replace canonical symbol for '__firstlineno__' with new int value 615
```

Because the packages are too old and incompatible with my python
version.
```sh
/Users/howardchu/hw/FinFin $ python3 --version
Python 3.13.7
```
There's also errors with psycopg2-binary and pydantic. Because they are
too old they can only be built on my system, but the build emits
failures.

So I'm upgrading these packages, hope they work for you as well. If they
don't could you please upgrade your python version to 3.13?

Signed-off-by: Howard Chu <howardchu95@gmail.com>